# Docker Compose configuration

services:
  # PostgreSQLサービス
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcp_ux
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
  
  # APIサービス
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-functions-new
    restart: always
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
      LOG_LEVEL: info
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - ./.env:/app/.env
      - /app/node_modules
      - /app/build
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:
    name: postgres_data

networks:
  app-network:
    driver: bridge