# Docker Compose configuration

services:
  # PostgreSQL service
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-mcp_ux}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init/${INIT_LANG:-ja}/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  
  # API service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-functions-new
    restart: always
    env_file:
      - ./.env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DISABLE_AUTH: ${DISABLE_AUTH:-true}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - ./.env:/app/.env
      - /app/node_modules
      - /app/build
    depends_on:
      - db
    networks:
      - app-network
  

volumes:
  postgres_data:
    name: postgres_data

networks:
  app-network:
    driver: bridge