# Cloud Build configuration for MCP Server
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mcp-server:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mcp-server:latest'
      - '-f'
      - 'mcp_server/Dockerfile'
      - 'mcp_server'
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mcp-server:$COMMIT_SHA'
    id: 'push-sha-image'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mcp-server:latest'
    id: 'push-latest-image'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mcp-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mcp-server:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--concurrency'
      - '${_CONCURRENCY}'
      - '--set-env-vars'
      - 'MCP_CLOUD_MODE=true,MCP_LOG_LEVEL=${_LOG_LEVEL},MCP_AUTH_PROVIDER=${_AUTH_PROVIDER}'
      - '--set-secrets'
      - 'MCP_API_KEY=${_MCP_API_KEY_SECRET}:latest,MCP_API_BASE_URL=${_API_BASE_URL_SECRET}:latest'
    id: 'deploy-cloud-run'
    waitFor: ['push-sha-image']

# Substitution variables with defaults
substitutions:
  _REGION: 'asia-northeast1'  # Tokyo region
  _MEMORY: '512Mi'
  _CPU: '1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _TIMEOUT: '900s'  # 15 minutes for SSE connections
  _CONCURRENCY: '100'
  _LOG_LEVEL: 'INFO'
  _AUTH_PROVIDER: 'api_key'
  _MCP_API_KEY_SECRET: 'mcp-api-key'
  _API_BASE_URL_SECRET: 'mcp-api-base-url'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/mcp-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/mcp-server:latest'